INDEPENDENT_VARIABLES: [SEED, POINTS.NUM_POINTS]
SAVE_PATHS: true

SEED: [0,1,2,3,4,5,6,7,8,9]

POINTS:
  TYPE: Uniform
  NUM_POINTS: [10]
  SPACE_SIZE: 40
  FIXED_Z: 5

PLANNER:
  TYPE: OurPlannerStochastic

  ENVIRONMENT: $env_settings.yaml

  TSP_LOCAL_SEARCH: false
  FAILURE_RISK: 0.1
  REFINE_TOURS: false
  PARALLEL_DP: true

  TAKEOFF_LANDING_TIME: 10.0
  UAV_BATTERY_TIME: 60.0
  CHARGE_RATE: 1

START_POINT: [0, 0]
END_POINT: [40, 40]
