INDEPENDENT_VARIABLES: [SEED, POINTS.NUM_POINTS]
SAVE_PATHS: true

SEED: [77, 0, 1, 2, 3, 4, 5, 6, 7, 8]

POINTS:
  TYPE: Uniform
  NUM_POINTS: [2, 3, 4]
  SPACE_SIZE: 4000
  FIXED_Z: 500

PLANNER: $planner_settings.yaml

START_POINT: [0, 0]
END_POINT: [4000, 4000]
