/estimator:
  ros__parameters:
    accel_process_noise: 0.024525
    alt_process_noise: 0.0001
    gps_ground_speed_threshold: 10.0
    gyro_process_noise: 0.013
    sigma_accel: 0.025
    sigma_e_gps: 0.001
    sigma_h_gps: 0.003
    sigma_mag: 0.0004
    sigma_n_gps: 0.001
    sigma_static_press: 1.0
    sigma_tilt_mag: 0.00035
    sigma_vd_gps: 0.001
    sigma_ve_gps: 0.0007
    sigma_vn_gps: 0.0007
    vel_horizontal_process_noise: 0.0001
    vel_vertical_process_noise: 0.0001
